FROM node:6.9.1

# Create app directory
RUN mkdir -p /usr/src/app

RUN git clone https://github.com/facebook/watchman.git \
    && cd watchman \
    && git checkout v3.1 \
    && ./autogen.sh \
    && ./configure \
    && make \
    && make install

WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

RUN ls

EXPOSE 4200
EXPOSE 41963
CMD [ "npm", "start" ]
